package com.st.ktv.entity;

public class TBArticleStatic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_static.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_static.cat_id
     *
     * @mbggenerated
     */
    private String catId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_static.cat_name
     *
     * @mbggenerated
     */
    private String catName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_article_static.code
     *
     * @mbggenerated
     */
    private String code;
    
    private String url;

    
    public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_static.id
     *
     * @return the value of tb_article_static.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_static.id
     *
     * @param id the value for tb_article_static.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_static.cat_id
     *
     * @return the value of tb_article_static.cat_id
     *
     * @mbggenerated
     */
    public String getCatId() {
        return catId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_static.cat_id
     *
     * @param catId the value for tb_article_static.cat_id
     *
     * @mbggenerated
     */
    public void setCatId(String catId) {
        this.catId = catId == null ? null : catId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_static.cat_name
     *
     * @return the value of tb_article_static.cat_name
     *
     * @mbggenerated
     */
    public String getCatName() {
        return catName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_static.cat_name
     *
     * @param catName the value for tb_article_static.cat_name
     *
     * @mbggenerated
     */
    public void setCatName(String catName) {
        this.catName = catName == null ? null : catName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_article_static.code
     *
     * @return the value of tb_article_static.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_article_static.code
     *
     * @param code the value for tb_article_static.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}