package com.st.ktv.entity;

public class TBAttribute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attribute.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attribute.key
     *
     * @mbggenerated
     */
    private String field;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_attribute.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attribute.id
     *
     * @return the value of tb_attribute.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attribute.id
     *
     * @param id the value for tb_attribute.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attribute.key
     *
     * @return the value of tb_attribute.key
     *
     * @mbggenerated
     */
    public String getKey() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attribute.key
     *
     * @param key the value for tb_attribute.key
     *
     * @mbggenerated
     */
    public void setKey(String key) {
        this.field = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_attribute.value
     *
     * @return the value of tb_attribute.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_attribute.value
     *
     * @param value the value for tb_attribute.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}