package com.st.ktv.entity;

import java.util.Date;

public class TBWechat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wechat.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wechat.appsecret
     *
     * @mbggenerated
     */
    private String appsecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wechat.wxname
     *
     * @mbggenerated
     */
    private String wxname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wechat.access_token
     *
     * @mbggenerated
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wechat.creattime
     *
     * @mbggenerated
     */
    private Date creattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wechat.other
     *
     * @mbggenerated
     */
    private String other;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wechat.appid
     *
     * @return the value of tb_wechat.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wechat.appid
     *
     * @param appid the value for tb_wechat.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wechat.appsecret
     *
     * @return the value of tb_wechat.appsecret
     *
     * @mbggenerated
     */
    public String getAppsecret() {
        return appsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wechat.appsecret
     *
     * @param appsecret the value for tb_wechat.appsecret
     *
     * @mbggenerated
     */
    public void setAppsecret(String appsecret) {
        this.appsecret = appsecret == null ? null : appsecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wechat.wxname
     *
     * @return the value of tb_wechat.wxname
     *
     * @mbggenerated
     */
    public String getWxname() {
        return wxname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wechat.wxname
     *
     * @param wxname the value for tb_wechat.wxname
     *
     * @mbggenerated
     */
    public void setWxname(String wxname) {
        this.wxname = wxname == null ? null : wxname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wechat.access_token
     *
     * @return the value of tb_wechat.access_token
     *
     * @mbggenerated
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wechat.access_token
     *
     * @param accessToken the value for tb_wechat.access_token
     *
     * @mbggenerated
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wechat.creattime
     *
     * @return the value of tb_wechat.creattime
     *
     * @mbggenerated
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wechat.creattime
     *
     * @param creattime the value for tb_wechat.creattime
     *
     * @mbggenerated
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wechat.other
     *
     * @return the value of tb_wechat.other
     *
     * @mbggenerated
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wechat.other
     *
     * @param other the value for tb_wechat.other
     *
     * @mbggenerated
     */
    public void setOther(String other) {
        this.other = other == null ? null : other.trim();
    }
}