package com.st.mapper.wxtour;

import java.util.List;

import com.st.javabean.pojo.wxtour.PseudoStatic;

public interface PseudoStaticMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pseudo_static
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pseudo_static
     *
     * @mbggenerated
     */
    int insert(PseudoStatic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pseudo_static
     *
     * @mbggenerated
     */
    int insertSelective(PseudoStatic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pseudo_static
     *
     * @mbggenerated
     */
    PseudoStatic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pseudo_static
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PseudoStatic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_pseudo_static
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PseudoStatic record);
    
    /**
     * @Title selectAll
     * @Description 查询所有的数据
     * @return List<PseudoStatic>
     */
    List<PseudoStatic> selectAll();
}