package com.st.mapper.wxtour;

import java.util.List;

import com.st.javabean.pojo.wxtour.TBArticleStatic;

public interface TBArticleStaticMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_static
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);
    
    /**
     * 删除所有
     * @return
     */
    int deleteAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_static
     *
     * @mbggenerated
     */
    int insert(TBArticleStatic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_static
     *
     * @mbggenerated
     */
    int insertSelective(TBArticleStatic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_static
     *
     * @mbggenerated
     */
    TBArticleStatic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_static
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TBArticleStatic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article_static
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TBArticleStatic record);
    
    /**
     * 获取数据库中所有的记录
     * @return
     */
    List<TBArticleStatic> selectAll();
}