package com.st.ktv.mapper;

import com.st.ktv.entity.JsapiTicket;


public interface JsapiTicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_jsapi_ticket
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String appid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_jsapi_ticket
     *
     * @mbggenerated
     */
    int insert(JsapiTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_jsapi_ticket
     *
     * @mbggenerated
     */
    int insertSelective(JsapiTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_jsapi_ticket
     *
     * @mbggenerated
     */
    JsapiTicket selectByPrimaryKey(String appid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_jsapi_ticket
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JsapiTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_jsapi_ticket
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JsapiTicket record);
}