package com.st.ktv.mapper;

import com.st.ktv.entity.TBAttribute;
import org.springframework.stereotype.Repository;

@Repository
public interface TBAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attribute
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attribute
     *
     * @mbggenerated
     */
    int insert(TBAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attribute
     *
     * @mbggenerated
     */
    int insertSelective(TBAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attribute
     *
     * @mbggenerated
     */
    TBAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TBAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TBAttribute record);
    
    
    /**
     * 根据key获取对象
     * @param key
     * @return
     */
    TBAttribute selectByKey(String key);
    
    /**
     * 根据key更新对象
     * @param record
     * @return
     */
    int updateByKey(TBAttribute record);
}