package com.st.ktv.mapper;

import com.st.ktv.entity.TBUserTransfer;
import org.springframework.stereotype.Repository;

@Repository
public interface TBUserTransferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_transfer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_transfer
     *
     * @mbggenerated
     */
    int insert(TBUserTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_transfer
     *
     * @mbggenerated
     */
    int insertSelective(TBUserTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_transfer
     *
     * @mbggenerated
     */
    TBUserTransfer selectByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_transfer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TBUserTransfer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_transfer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TBUserTransfer record);
}