package com.st.ktv.mapper;

import com.st.ktv.entity.TBWechat;

public interface TBWechatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wechat
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String appid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wechat
     *
     * @mbggenerated
     */
    int insert(TBWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wechat
     *
     * @mbggenerated
     */
    int insertSelective(TBWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wechat
     *
     * @mbggenerated
     */
    TBWechat selectByPrimaryKey(String appid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wechat
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TBWechat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_wechat
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TBWechat record);
}