package com.st.javabean.pojo.wxtour;

import java.util.Date;

public class JsapiTicket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jsapi_ticket.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jsapi_ticket.ticket
     *
     * @mbggenerated
     */
    private String ticket;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_jsapi_ticket.creattime
     *
     * @mbggenerated
     */
    private Date creattime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jsapi_ticket.appid
     *
     * @return the value of tb_jsapi_ticket.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jsapi_ticket.appid
     *
     * @param appid the value for tb_jsapi_ticket.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jsapi_ticket.ticket
     *
     * @return the value of tb_jsapi_ticket.ticket
     *
     * @mbggenerated
     */
    public String getTicket() {
        return ticket;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jsapi_ticket.ticket
     *
     * @param ticket the value for tb_jsapi_ticket.ticket
     *
     * @mbggenerated
     */
    public void setTicket(String ticket) {
        this.ticket = ticket == null ? null : ticket.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_jsapi_ticket.creattime
     *
     * @return the value of tb_jsapi_ticket.creattime
     *
     * @mbggenerated
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_jsapi_ticket.creattime
     *
     * @param creattime the value for tb_jsapi_ticket.creattime
     *
     * @mbggenerated
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }
}