package com.st.javabean.pojo.wxtour;

import java.util.Date;

public class PseudoStatic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pseudo_static.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pseudo_static.seo_url
     *
     * @mbggenerated
     */
    private String seoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pseudo_static.real_url
     *
     * @mbggenerated
     */
    private String realUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pseudo_static.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * 第二个正则的位置，可以做参数使用
     */
    private String param;
    
    /**
     * 默认的额外字段，以便不时之需
     */
    private String remark;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pseudo_static.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pseudo_static.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pseudo_static.is_delete
     *
     * @mbggenerated
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_pseudo_static.delete_time
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pseudo_static.id
     *
     * @return the value of tb_pseudo_static.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pseudo_static.id
     *
     * @param id the value for tb_pseudo_static.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pseudo_static.seo_url
     *
     * @return the value of tb_pseudo_static.seo_url
     *
     * @mbggenerated
     */
    public String getSeoUrl() {
        return seoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pseudo_static.seo_url
     *
     * @param seoUrl the value for tb_pseudo_static.seo_url
     *
     * @mbggenerated
     */
    public void setSeoUrl(String seoUrl) {
        this.seoUrl = seoUrl == null ? null : seoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pseudo_static.real_url
     *
     * @return the value of tb_pseudo_static.real_url
     *
     * @mbggenerated
     */
    public String getRealUrl() {
        return realUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pseudo_static.real_url
     *
     * @param realUrl the value for tb_pseudo_static.real_url
     *
     * @mbggenerated
     */
    public void setRealUrl(String realUrl) {
        this.realUrl = realUrl == null ? null : realUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pseudo_static.description
     *
     * @return the value of tb_pseudo_static.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pseudo_static.description
     *
     * @param description the value for tb_pseudo_static.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    
    public String getParam() {
		return param;
	}

	public void setParam(String key) {
		this.param = key;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pseudo_static.create_time
     *
     * @return the value of tb_pseudo_static.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pseudo_static.create_time
     *
     * @param createTime the value for tb_pseudo_static.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pseudo_static.update_time
     *
     * @return the value of tb_pseudo_static.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pseudo_static.update_time
     *
     * @param updateTime the value for tb_pseudo_static.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pseudo_static.is_delete
     *
     * @return the value of tb_pseudo_static.is_delete
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pseudo_static.is_delete
     *
     * @param isDelete the value for tb_pseudo_static.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_pseudo_static.delete_time
     *
     * @return the value of tb_pseudo_static.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_pseudo_static.delete_time
     *
     * @param deleteTime the value for tb_pseudo_static.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
}